"""PLT-Optimizer: Deterministic cross-platform Python tool for optimizing geometric toolpaths.

This package provides tools for parsing, analyzing, and optimizing HPGL/PLT plotter files
generated by Cadlink EngraveLab Expert v10 for Vision 1624 engraving tables.
"""

__version__ = "1.2.11"
__author__ = "PLT-Optimizer Team"

from plt_optimizer.core.parser import PLTParser
from plt_optimizer.core.writer import PLTWriter

__all__ = [
    "__version__",
    "PLTParser",
    "PLTWriter",
]
