"""PLT-Optimizer generate module.

This module provides the generation pipeline for creating PLT files from
YAML job specifications.
"""

from plt_optimizer.generate.layout import (
    DEFAULT_PLATE_HEIGHT,
    DEFAULT_PLATE_WIDTH,
    LayoutFitError,
    PackedLabel,
    PackedPlate,
    generate_layout,
    generate_layout_with_bounds,
    initialize_packer,
    unroll_labels,
)
from plt_optimizer.generate.resolution import (
    DEFAULT_CHAR_SPACING,
    DEFAULT_LINE_SPACING,
    DEFAULT_MARGIN,
    DEFAULT_TEXT_HEIGHT,
    IDEAL_CUTTER_MAP,
    ResolvedHoleSpec,
    ResolvedLabel,
    ResolvedTextLine,
    calculate_label_dimensions,
    get_cutter_diameter,
    resolve_job_spec,
)
from plt_optimizer.generate.schema import (
    HoleLocation,
    HoleSpec,
    JobSpec,
    LabelAttributes,
    LabelSpec,
    PlateSpec,
    TextAttributes,
    TextLine,
    parse_yaml,
)
from plt_optimizer.generate.vectorize import (
    LAYER_BOUNDARY,
    LAYER_HOLES,
    LAYER_TEXT,
    POINTS_PER_INCH,
    TEXT_BLOCK_HEIGHT_PER_SIZE,
    assemble_plt_from_rendered_labels,
    export_and_optimize,
    export_and_optimize_phase3,
    export_to_plt,
    translate_plt_coordinates,
    vectorize_plate,
    vectorize_plates,
)

__all__ = [
    "DEFAULT_CHAR_SPACING",
    "DEFAULT_LINE_SPACING",
    "DEFAULT_MARGIN",
    "DEFAULT_PLATE_HEIGHT",
    "DEFAULT_PLATE_WIDTH",
    "DEFAULT_TEXT_HEIGHT",
    "HoleLocation",
    "HoleSpec",
    "IDEAL_CUTTER_MAP",
    "JobSpec",
    "LAYER_BOUNDARY",
    "LAYER_HOLES",
    "LAYER_TEXT",
    "LabelAttributes",
    "LabelSpec",
    "LayoutFitError",
    "POINTS_PER_INCH",
    "PackedLabel",
    "PackedPlate",
    "PlateSpec",
    "ResolvedHoleSpec",
    "ResolvedLabel",
    "ResolvedTextLine",
    "TextAttributes",
    "TextLine",
    "TEXT_BLOCK_HEIGHT_PER_SIZE",
    "assemble_plt_from_rendered_labels",
    "calculate_label_dimensions",
    "export_and_optimize",
    "export_and_optimize_phase3",
    "export_to_plt",
    "generate_layout",
    "generate_layout_with_bounds",
    "get_cutter_diameter",
    "initialize_packer",
    "parse_yaml",
    "resolve_job_spec",
    "translate_plt_coordinates",
    "unroll_labels",
    "vectorize_plate",
    "vectorize_plates",
]
