"""PLT-Optimizer generate module.

This module provides the generation pipeline for creating PLT files from
YAML job specifications.
"""

from plt_optimizer.generate.label_renderer import (
    LabelRenderError,
    RenderedLabel,
    assert_no_collisions,
)
from plt_optimizer.generate.layout import (
    DEFAULT_PLATE_HEIGHT,
    DEFAULT_PLATE_WIDTH,
    LayoutFitError,
    PackedLabel,
    PackedPlate,
    generate_layout,
    generate_layout_with_bounds,
    initialize_packer,
    unroll_labels,
)
from plt_optimizer.generate.resolution import (
    DEFAULT_CHAR_SPACING,
    DEFAULT_LINE_SPACING,
    DEFAULT_MARGIN,
    DEFAULT_TEXT_HEIGHT,
    IDEAL_CUTTER_MAP,
    ResolvedHoleSpec,
    ResolvedLabel,
    ResolvedTextLine,
    build_cutter_pen_map,
    calculate_label_dimensions,
    get_cutter_diameter,
    resolve_job_spec,
)
from plt_optimizer.generate.schema import (
    DEFAULT_HOLE_DIAMETER,
    HOLE_LOCATION_GROUPS,
    HoleLocation,
    HoleSpec,
    JobSpec,
    LabelAttributes,
    LabelSpec,
    PlateSpec,
    TextAttributes,
    TextLine,
    parse_yaml,
)
from plt_optimizer.generate.substitution import (
    DEFAULT_REPLACEMENT_DELIMITER,
    SubstitutionError,
    expand_job_spec,
    expand_label_with_replacements,
    load_replacement_file,
)
from plt_optimizer.generate.vectorize import (
    LAYER_BOUNDARY,
    LAYER_HOLES,
    LAYER_TEXT,
    POINTS_PER_INCH,
    TEXT_BLOCK_HEIGHT_PER_SIZE,
    PerCutterExport,
    assemble_plt_from_rendered_labels,
    export_and_optimize,
    export_and_optimize_phase3,
    export_per_cutter_plts,
    export_to_plt,
    extract_layer_from_plt_text,
    extract_pens_from_plt_text,
    plt_has_geometry,
    translate_plt_coordinates,
    vectorize_plate,
    vectorize_plates,
    write_default_plots,
)

__all__ = [
    "DEFAULT_CHAR_SPACING",
    "PerCutterExport",
    "DEFAULT_HOLE_DIAMETER",
    "DEFAULT_LINE_SPACING",
    "DEFAULT_MARGIN",
    "DEFAULT_PLATE_HEIGHT",
    "DEFAULT_PLATE_WIDTH",
    "DEFAULT_REPLACEMENT_DELIMITER",
    "DEFAULT_TEXT_HEIGHT",
    "HOLE_LOCATION_GROUPS",
    "HoleLocation",
    "HoleSpec",
    "IDEAL_CUTTER_MAP",
    "JobSpec",
    "LAYER_BOUNDARY",
    "LAYER_HOLES",
    "LAYER_TEXT",
    "LabelAttributes",
    "LabelRenderError",
    "LabelSpec",
    "LayoutFitError",
    "POINTS_PER_INCH",
    "PackedLabel",
    "PackedPlate",
    "PlateSpec",
    "RenderedLabel",
    "SubstitutionError",
    "ResolvedHoleSpec",
    "ResolvedLabel",
    "ResolvedTextLine",
    "TextAttributes",
    "TextLine",
    "TEXT_BLOCK_HEIGHT_PER_SIZE",
    "assemble_plt_from_rendered_labels",
    "assert_no_collisions",
    "build_cutter_pen_map",
    "calculate_label_dimensions",
    "expand_job_spec",
    "expand_label_with_replacements",
    "export_and_optimize",
    "export_and_optimize_phase3",
    "export_per_cutter_plts",
    "export_to_plt",
    "extract_layer_from_plt_text",
    "extract_pens_from_plt_text",
    "generate_layout",
    "generate_layout_with_bounds",
    "get_cutter_diameter",
    "plt_has_geometry",
    "initialize_packer",
    "load_replacement_file",
    "parse_yaml",
    "resolve_job_spec",
    "translate_plt_coordinates",
    "unroll_labels",
    "vectorize_plate",
    "vectorize_plates",
    "write_default_plots",
]
